### ISSUE TITLE
Soft delete of custom roles can result in (re)build failure

### ISSUE THREAD

**Issue by henrybell** [cloudspannerecosystem/autoscaler#115]
For the custom roles created via Terraform:

- `spannerAutoscalerMetricsViewer`
- `spannerAutoscalerCapacityManager`

Because a `delete` operation actuated by `terraform destroy` is only a [soft delete](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role), this can result in an inability to (re)build during a certain time window (7-37 days):

`"You can't create a role_id (spannerAutoscalerCapacityManager) which has been marked for deletion."`

To work around this, a random string may be appended to the role name(s), circumventing the restriction.

**Comment by davidcueva** [comment]
+1 to the random string solution

**Comment by henrybell** [comment]
Fixed in #116
