### ISSUE TITLE
Same spanner instance for storing state implications

### ISSUE THREAD

**Issue by navneet-kumar-lloyds** [cloudspannerecosystem/autoscaler#119]
Hi Team,
Need quick help in checking what will be implications of storing the state in the same spanner instance that we are autoscaling by the tool.

Plz feel free to close this once answered.

Thanks!

**Comment by davidcueva** [comment]
Hi Navneet

In the vast majority of cases, there should be no issue. However, if the instance is extremely overloaded, in a way that requests start to [timeout](https://cloud.google.com/spanner/docs/deadline-exceeded), then the Autoscaler might not be able to retrieve its state, resulting in unsuccessful scaling attempts.

The Autoscaler is there to avoid an overloading scenario in the first place, so to reach a point of extreme load with the Autoscaler enabled, the instance must have already hit its configured maxSize, run out of quota or hit an unmanageable traffic peak very quickly.
