### ISSUE TITLE
Notifications on scale up/down events

### ISSUE THREAD

**Issue by bgood** [cloudspannerecosystem/autoscaler#12]
When the autoscaler scales up or down a Cloud Spanner instance it would be nice if it could notify users that it made a change to a Cloud Spanner instance.

Useful notification channels could be:
* Chat services such as Slack or Google Chat
* Email

Useful information could be:
* Spanner Instance 
* Observed Metric, value and threshold
* Number of nodes added or removed

**Comment by henrybell** [comment]
Fixed by #91.
