### ISSUE TITLE
Will this repository be closed in the near future?

### ISSUE THREAD

**Issue by iwata** [cloudspannerecosystem/autoscaler#139]
Will the next commit allow me to set up an autoscaler in Spanner?
https://github.com/googleapis/googleapis/commit/d6467dbbb985d1777b6ab931ce09b8b3b1a7be08
In other words, will this project be closed?

**Comment by henrybell** [comment]
There are no plans to deprecate the OSS Spanner Autoscaler (i.e. this repository) in the near term.

While there is a native Spanner autoscaling capability in development, we can’t comment on its progress, features, or the schedule for its potential release.
