### ISSUE TITLE
Feature Request: More configurable thresholds per spanner instance

### ISSUE THREAD

**Issue by itsdax** [cloudspannerecosystem/autoscaler#23]
Currently, the following fields are hard coded into the code:

- OVERLOAD_THRESHOLD for high priority CPU - currently at 90%
- regional_threshold for high priority CPU - currently at 65%

There are a couple others, but these are the main ones that are likely to impact Spanner performance.
It would be good to have these configurable for each spanner instance.

Spanner is a P0 dependency for some of our services and we already notice latency spikes at 65% high priority CPU utilization. Based on this, 90% is a too high of an overload threshold for us. 

We currently manually change these thresholds ourselves when we deploy the autoscaler to 55% target and 75% overload.

**Comment by davidcueva** [comment]
We added custom thresholds, let us know what you think
https://github.com/cloudspannerecosystem/autoscaler/blob/master/poller/README.md#custom-thresholds
