### ISSUE TITLE
Add alternative scheduler for Cloud Scheduler

### ISSUE THREAD

**Issue by bgood** [cloudspannerecosystem/autoscaler#30]
Cloud Scheduler is currently the only supported scheduler mechanism. While Cloud Scheduler is serverless, which has the benefits of having a low maintenance overhead there are some limitations:
 - Publishing Pub/Sub messages cross project
 - Lack of VPC service controls
 - Requires AppEngine

These could be worked around with an alternative scheduler, perhaps a Spring base scheduler or Kubernetes Cron Job.

**Comment by davidcueva** [comment]
Solved by #77
