### ISSUE TITLE
Best practice autoscaling threshold configuration?

### ISSUE THREAD

**Issue by alexlo03** [cloudspannerecosystem/autoscaler#343]
Hello,

Out of the box this project configures the high priority CPU threshold at 65% (regional), 45% (multi-regional) with a margin of 5%, which means that it only autoscales when it sees 70% (regional) or 50% (multi-regional)

Is this advised for Production use, or should we set the thresholds lower?

Refs

https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L100-L101

https://cloud.google.com/spanner/docs/cpu-utilization#recommended-max

**Comment by davidcueva** [comment]
hi Alex, 

these are the thresholds recommended by our Product Managers. 
They are a good starting point that can be used in production. 

That being said, observe your resource utilization before and after, and adjust them if necessary.

David
