### ISSUE TITLE
Best practice poller schedule?

### ISSUE THREAD

**Issue by alexlo03** [cloudspannerecosystem/autoscaler#344]
Hello,

Out of the box [the poller function runs every 2m](https://github.com/cloudspannerecosystem/autoscaler/blob/main/terraform/modules/scheduler/variables.tf#L27), but then queries metrics for only [the last 60s](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L99), so the poller could miss a spike in the 60s that is not examined. Is this recommended or should the poller schedule be updated to once per minute?

**Comment by davidcueva** [comment]
Hi Alex

The `period` key/value pair in the metrics does *not* limit the query to the last 60s.
It is actually the `alignment period`, which is used to divide the time series into buckets, and then calculate a single value for each of those periods/buckets using the selected `aligner`. [Here's more information](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#Aligner).

https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L98-L99

David

**Comment by alexlo03** [comment]
@davidcueva  Thanks for the answer. Sorry for the dumb questions - does this describe the behavior:

Every 2m the poller runs- the metrics query is:

[A 5 minute interval (aka window)](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L199) (assuming default 60s periods) 

so there are 5 periods of 60s: it gets the max value for each period. The reducer is a no-op because there is only one data series. [the group by location](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L226) means that a series is returned from each location in the case of a multi-regional instance.

The code gets back the data points and [iterates through them](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/poller/poller-core/index.js#L231-L247) identifying the max value it saw and which location/region it came from.

Is this accurate?


==

This means that if you have a high utilization value, it will be in two consecutive runs - example log:

<img width="893" alt="Screenshot 2024-07-09 at 11 00 43" src="https://github.com/cloudspannerecosystem/autoscaler/assets/1072146/ed347d2c-8d85-40ef-9543-339067035b73">

and the [scaleOutCoolingMinutes](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/scaler/README.md?plain=1#L107) is the only thing that stops a double scaling



== 
side note

If anyone is interested you can do the query: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list

```metric.type = "spanner.googleapis.com/instance/cpu/utilization_by_priority" AND resource.labels.instance_id="instance_name" AND metric.label.priority="high"```

<img width="451" alt="Screenshot 2024-07-09 at 10 15 06" src="https://github.com/cloudspannerecosystem/autoscaler/assets/1072146/cd310260-9bbe-41c9-b9b3-750d6c74940b">

**Comment by davidcueva** [comment]
There are no dumb questions. 

Yes, that describes the current behaviour, but one important detail is that that [scaleOutCoolingMinutes](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/scaler/README.md?plain=1#L107) is **not** the only thing that stops a double scaling. We register the [Long Running Operation (LRO)](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/scaler/scaler-core/index.js#L137C12-L137C21) returned by the scaling request, and we [prevent new scaling requests if there is an ongoing LRO](https://github.com/cloudspannerecosystem/autoscaler/blob/4248b1a1400baa06cd99b0d8ca25a37dc52e706f/src/scaler/scaler-core/index.js#L378). Even without this check, if you send multiple scaling requests to Spanner and there is already an ongoing scaling process, then the new request will be rejected by Spanner.
