### ISSUE TITLE
Do we have option to identify minNodes and MaxNodes automatically as per load?

### ISSUE THREAD

**Issue by awadheshgupta** [cloudspannerecosystem/autoscaler#36]
Do we have option to identify minNodes and MaxNodes automatically as per load?

Rather expecting  user to provide minNodes and MaxNodes, its better to identify nodes size automatically as per intelligence identified during load throughput KPI.

With regards,
Awadhesh Gupta

**Comment by davidcueva** [comment]
Hi Awadesh
We currently do not have an option to automatically identify minNodes and maxNodes.

I think it is an interesting idea, and I can see a recommendation engine that could learn from the load and recommend optimal limits.  However, maxNodes is commonly used as a cost control measure, so applying recommendations should be optional.

We do not have this feature in the roadmap, but as always we can receive contributions from the community.

David

**Comment by davidcueva** [comment]
You're welcome !
