### ISSUE TITLE
Implement support for Spanner Granular Instances

### ISSUE THREAD

**Issue by davidcueva** [cloudspannerecosystem/autoscaler#44]
Context:
https://cloud.google.com/blog/products/databases/get-more-out-of-spanner-with-granular-instance-sizing

**Comment by davidcueva** [comment]
- [ ] Add new parameters to the Poller
- [ ] Add new parameters to the Scaler
- [ ] Add support in scaling algorithms
- [ ] Testing plan
- [ ] Update docs

**Comment by bgood** [comment]
Need to update Terraform examples
