### ISSUE TITLE
Using only units + minSize/maxSize results in default minNodes/maxNodes overriding provided minSize/maxSize

### ISSUE THREAD

**Issue by nnutter** [cloudspannerecosystem/autoscaler#61]
Given,

```js
spanners[sIdx] = {...nodesDefaults, ...spanners[sIdx]};
if(spanners[sIdx].minNodes && spanners[sIdx].minSize != spanners[sIdx].minNodes) {
    log(`DEPRECATION: minNodes is deprecated, remove minNodes from your config and instead use: units = 'NODES' and minSize = ${spanners[sIdx].minNodes}`,
       'WARNING');
    spanners[sIdx].minSize = spanners[sIdx].minNodes;
}
```

Because this logic does not care that `minSize` was specified and because `minNodes` is provided by `nodesDefaults` if a payload config does not provide `minNodes` then the default `minNodes` overrides the provided `minSize`.

Same all applies to `maxSize`/`maxNodes`.

Also note that the warning for the `maxNodes` case accidentally mentions `minNodes`.

**Comment by nnutter** [comment]
My solution was to remove `minNodes`/`maxNodes` from `nodesDefaults`.

**Comment by davidcueva** [comment]
Merged PR
