### ISSUE TITLE
404 for some important links in poller read me page

### ISSUE THREAD

**Issue by yuanyuan-gl** [cloudspannerecosystem/autoscaler#70]
From https://github.com/cloudspannerecosystem/autoscaler/tree/master/poller page

The links in following paragraph are all 404, thus it lacks of instructions on how to configure custom metrics. 

[Cloud Spanner metric](https://github.com/cloudspannerecosystem/autoscaler/blob/master/poller/spanner-metrics) and [filter](https://github.com/cloudspannerecosystem/autoscaler/blob/master/poller/time-series-filters) that should be used when querying for data. The Autoscaler will automatically add the filter expressions for [Spanner instance resources, instance id](https://github.com/cloudspannerecosystem/autoscaler/blob/master/poller/spanner-filter) and project id.

**Comment by davidcueva** [comment]
These links are fixed in the Poller page.
